routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
..
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,"index"])->name("index");

Route::post('/add-panier' ,[HomeController::class,"addPanier"])->name("add-panier");
Route::get('/show-panier' ,[HomeController::class,"showPanier"])->name("show-panier");
Route::get('/clear-panier' ,[HomeController::class,"clearPanier"])->name("clear-panier-item");
Route::post('/remove-panier-item' ,[HomeController::class,"removePanier"])->name("remove-panier-item");

Route::get("/categories/search", [CategorieController::class,"search"])->name("categories.search");
Route::get("/produits/search", [ProduitController::class,"search"])->name("produits.search");

Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("commandes",CommandeController::class);

// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    //

    public function index(){
        $produits = Produit::paginate(12);
        return view("home.index", compact("produits"));
    }
    public function addPanier(Request $request){

        $produits = [
            "id"=>$request->id,
            "designation"=>$request->designation,
            "prix_u"=>$request->prix_u,
            "qnt"=>$request->qnt,
            "photo"=>$request->photo,
        ];
        session()->push("user.produits",$produits);
        return $this->index();
    }
    public function showPanier(){

        $produits = session()->get("user.produits");
        return view("home.show",compact("produits"));
    }

    public function removePanier(Request $request){
        $produits = $request->session()->get('user.produits');
        foreach($produits as $key=>$prod){
            if($prod["id"] == $request->id) unset($produits[$key]);
        };
        session()->put("user.produits",$produits);
        return redirect()->route('show-panier');
    }
    public function sumPanier(){
        
    }
    public function clearPanier(Request $request){
        $request->session()->flush();
        return redirect()->route('index');
    }
    
}

resources/views/home/index.blade.php
@extends('layouts.admin')
@section('title', 'Home Page')
@section('content')



    {{-- Search and Ajouter --}}
    <h1 class="mt-5 mb-3">Welcome GestionE</h1>

    {{-- reset --}}
    <a href="{{ route('produits.index') }}">list des produits</a>

    <div class="row gap-5">
        <a href="{{ route('show-panier') }}">Show Panier</a>
        @foreach ($produits as $prod)
            <form method="POST" action="{{ route('add-panier') }}/" class="card col-4" style="width: 18rem;">
                @csrf
                <img src="{{ asset("storage/$prod->photo") }}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{ $prod->designation }}</h5>
                    <p class="card-text">{{ $prod->prix_u }}</p>
                    {{-- hidden inputs --}}

                    <input value="{{$prod->id}}" type="hidden" name="id">
                    <input value="{{$prod->prix_u}}" type="hidden" name="prix_u">
                    <input value="{{$prod->designation}}" type="hidden" name="designation">
                    <input value="{{$prod->photo}}" type="hidden" name="photo">

                    <input placeholder="quantity" class="form-control mb-3" type="number" name="qnt">

                    <button type="submit" href="#" class="btn btn-primary">Detailt</button>
                    <button type="submit" class="btn btn-primary">Ajouter au panier</button>
                </div>
            </form>
        @endforeach
    </div>

    {{ $produits->links() }}
@endsection

resources/views/home/show.blade.php
@extends('layouts.admin')
@section('title', 'Home Page')
@section('content')

    <a href="{{ route('clear-panier-item') }}">Clear Panier</a>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Icon</th>
                <th scope="col">designation</th>
                <th scope="col">prix</th>
                <th scope="col">quantity</th>
                <th scope="col">action</th>
            </tr>
        </thead>
        <tbody>
            @php($total = 0)
            @foreach ($produits as $prod)
                <tr>
                    <td>
                        <img height="50" src={{ asset("storage/" . $prod["photo"]) }} alt="">
                    </td>
                    <td> {{ $prod['designation'] }} </td>
                    <td> {{ $prod['prix_u'] }} </td>
                    @php($total += $prod['prix_u'] * $prod['qnt'])
                    <td> {{ $prod['qnt'] }} </td>
                    <td>
                        <form method="POST" action="{{ route('remove-panier-item') }}/?id={{ $prod['id'] }}">
                            @csrf
                            <button class="btn btn-danger" type="submit"><img src="{{ asset('/delete.png') }}"></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            <tr>
                <td colspan="4" class="h3">Total: {{ $total }} </td>
                <td>
                    <form action='{{route("commandes.create")}}'>
                        @csrf
                        <button class="btn btn-primary" type="submit">Command</button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
@endsection